covid_starterpack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('covid_kit/', include('covid_kit.urls', namespace='covid_kit')),
    path('daftar-rs/', include(('list_rs.urls', 'list_rs'), namespace='list_rs')),
    path('daftarkasus/', include('list_kasus.urls',namespace ='listkasus')),
    path('berita/', include('berita.urls')),
    path('contact/', include('contact.urls')),
    path('faq/', include('faq.urls', namespace='faq')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls', namespace='register')),
]

faq/urls.py
from django.urls import path, include

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq, name='faq'),
    path('info/', views.informasi, name='info'),
    path('list-pertanyaan/', views.list_pertanyaan, name='list-pertanyaan'),
    path('jawab/P<int:id_pertanyaan>/', views.jawab, name='jawab'),
    path('list-FAQ/', views.list_faq, name='list-faq'),
    path('detail/P<int:id_pertanyaan>/', views.detail, name='detail'),
]

list_kasus/urls.py
from django.urls import path
from . import views
app_name = 'list_kasus'

urlpatterns = [

    path('',views.list_kasus,name = 'list_kasus'),
    path('kasus_detail/<int:pk>/',views.kasus_detail, name = 'kasusdetail'),
    path('tambahkasus/', views.tambah_kasus, name='tambahkasus'),
    path('kasusprovinsi/', views.kasus_provinsi, name='kasusprovinsi'),
    path('kasusinput/', views.kasus_input, name='kasusinput'),
    path('datainput/', views.daftar_input, name = 'datainput'),
    path('data/',views.api_kasus_provinsi,name='data'),
    path('dataIndonesia/',views.api_kasus_Indo,name='dataIndonesia'),
]

list_kasus/models.py
from django.db import models

# Create your models here.
class ListKasus(models.Model):
    nama_daerah = models.CharField(max_length=50)
    jumlah_total = models.IntegerField()
    kasus_sembuh = models.IntegerField()
    kasus_meninggal = models.IntegerField()
    tanggal = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.nama_daerah

class KasusIndo(models.Model):
    nama = models.CharField(max_length=50)
    jumlah_total = models.IntegerField()
    kasus_sembuh = models.IntegerField()
    kasus_meninggal = models.IntegerField()
    tanggal = models.DateTimeField(auto_now= True)

    def __str__(self):
        return self.nama

list_kasus/forms.py
from django import forms
from .models import ListKasus

class formKasus(forms.ModelForm):
    class Meta:
        model = ListKasus
        fields = "__all__"

        widgets = {
            'nama_daerah' : forms.TextInput(attrs={'required': True,'id':'namee'}),
            'jumlah_total' : forms.NumberInput(attrs={'required': True,'id':'jumlahtotal'}),
            'kasus_sembuh' : forms.NumberInput(attrs={'required': True,'id':'jumlahsembuh'}),
            'kasus_meninggal' : forms.NumberInput(attrs={'required': True,'id':'jumlahmeninggal'}),
        }

list_kasus/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import requests
import json
from .models import ListKasus,KasusIndo
from . import models
from .forms import formKasus
from operator import itemgetter

# Create your views here.

def list_kasus(request):
    list_kasus = ListKasus.objects.all()
    
    kasus = KasusIndo.objects.all()

    a = []
    a.append(kasus)
    if all(x for x in a) == False:
        models.KasusIndo.objects.create(nama='Indonesia',jumlah_total='463007',kasus_sembuh='388094',kasus_meninggal='15148')
    else : 
        pass
    kasus = KasusIndo.objects.all()
    context = {'list_kasus':list_kasus,'kasus':kasus}
    return render(request,'list_kasus/listkasus.html',context)


def kasus_detail(request, pk):
    kasus = ListKasus.objects.all().filter(id=pk)
    list_kasus = ListKasus.objects.all()
    context = {'kasus': kasus,'list_kasus':list_kasus}
    return render(request,'list_kasus/kasusdetail.html',context)

def tambah_kasus(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ("/accounts/login/", request.path))
    form = formKasus()
    response_data = {}
    if(request.method == 'POST'):
        form = formKasus(request.POST)
        if(form.is_valid()):
            data = form.cleaned_data
            lisstkasus = ListKasus()
            nama_daerah =  data['nama_daerah']
            jumlah_total = data['jumlah_total']
            kasus_sembuh = data['kasus_sembuh']
            kasus_meninggal = data['kasus_meninggal']
            ListKasus.objects.create(
                nama_daerah = request.POST.get('nama_daerah'),
                jumlah_total = request.POST.get('jumlah_total'),
                kasus_sembuh = request.POST.get('kasus_sembuh'),
                kasus_meninggal = request.POST.get('kasus_meninggal'),
            )
            response_data['nama_daerah'] = nama_daerah
            response_data['jumlah_total'] = jumlah_total
            response_data['kasus_sembuh'] = kasus_sembuh
            response_data['kasus_meninggal'] = kasus_meninggal

            return JsonResponse(response_data)
    
    context = {'form':form}
    return render(request,'list_kasus/tambahkasus.html',context)

def kasus_provinsi(request):
    return render(request,'list_kasus/kasusprovinsi.html')

def kasus_input(request):
    return render(request,'list_kasus/kasusinputan.html')

def api_kasus_provinsi(request):
    url = "https://indonesia-covid-19.mathdro.id/api/provinsi"
    ret = requests.get(url)
    data = json.loads(ret.content)
    return JsonResponse(data, safe=False)

def api_kasus_Indo(request):
    url = "https://apicovid19indonesia-v2.vercel.app/api/indonesia"
    ret = requests.get(url)
    data = json.loads(ret.content)
    return JsonResponse(data, safe=False)

def daftar_input(request):
    kasuz = ListKasus.objects.all()
    result = []
    for i in kasuz:
        temp = dict()
        temp['nama_daerah'] = i.nama_daerah
        temp['jumlah_total'] = i.jumlah_total
        temp['kasus_sembuh'] = i.kasus_sembuh
        temp['kasus_meninggal'] = i.kasus_meninggal
        temp['tanggal'] = i.tanggal
        temp['pk'] = i.pk
        result.append(temp)
    context = {
        'result': result,
    }
    return JsonResponse(context)

list_kasus/templates/list_kasus/kasusdetail.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}


  {% block meta%}
  <link rel="stylesheet" href="{% static 'list_kasus/styleR.css' %}">
  {% endblock meta%}


<body>
  {% block content %}
    <div class ="container" style="margin-top: 100px;">
        {% for i in kasus%}
        <h2>Jumlah Kasus Covid di Daerah {{i.nama_daerah}} Saat Ini</h2>
        <div class ="row">
            <div class="col-md-4 text-center" >Kasus Terkonfirmasi <div class='card' style='width:100%;'>{{i.jumlah_total}}</div></div>
            <div class="col-md-4 text-center">Kasus Sembuh <div class='card' style='width:100%;'>{{i.kasus_sembuh}}</div></div>
            <div class="col-md-4 text-center">Kasus Meninggal <div class='card' style='width:100%;'>{{i.kasus_meninggal}}</div></div>
        </div>
        <p>Tanggal Dibuat {{i.tanggal}}</p>
        {% endfor %}
        <p>Cari Kasus di Daerahmu
              
        </p>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="asw" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Cari Daerahmu
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for i in list_kasus %}
              <a class="dropdown-item" href="{% url 'listkasus:kasusdetail' i.pk %}">{{i.nama_daerah}}</a>
                {% endfor %}
            </div>
          </div>
          <br>
          {% if user.is_authenticated %}
        <div>Mengetahui Jumlah Kasus di Daerahmu? Silahkan Tambahkan Kasus
            <a class="btn btn-info" href="{% url 'listkasus:tambahkasus' %}">Tambah Kasus</a>
        </div>
          {% else %}
          <div id="logon">Silahkan login untuk menambahkan kasus yang kamu ketahui di daerahmu, klik mengerti untuk menghilangkan pemberitahuan <p></p><a href ="#" id="ngerti" style="color:rgb(228, 59, 81);">Mengerti</a></div>
          {% endif %}
          <br>
            <div>
              <a class ="btn btn-secondary" href="{% url 'listkasus:kasusprovinsi' %}">berikut list kasus pada tiap provinsi di Indonesia</a>
            </div>
        <div class='text-right' id='backtotheback'>
        <a class="btn btn-info" href='/daftarkasus' >Kembali</a>
        </div>
        </div>
        <br>
    
</body>
<script>
  $("#ngerti").click(function(){
    $("#logon").hide();
  });
</script>
{% endblock content %}

list_kasus/templates/list_kasus/kasusinputan.html
<html>
    {% extends 'base.html'%}
    {% load static %}
    {% block content %}
<head>
    {% block meta%}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"/>
 
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.23/datatables.min.js"></script>
    <style>
        footer,.navbar-brand,.nav-item{
        color: black;
        }
        #bodskuy{
            background-color: #4ECDC4;
        }
        table,th,td{
            border: black;
        }
        /* #daftar tbody tr.selected{
            color:black;
            background-color: #eeeeee;
        } */
    </style>
    {% endblock meta%}
</head>
<body>
    <div class = "titlee" style="margin-top: 100px;">
        <h1 class="text-center" style="color:white;"> Kasus COVID-19 di Daerah </h1>
        
    </div>
    <div id="bodskuy">
        <br><br>
        <main class="container">
        <table class="table cell-border" id="daftar" style="color: black;">
        <thead style="color: black; background-color: gray;" >
            <tr>
                <th>No</th>
                <th>Provinsi</th>
                <th>Kasus Terkonfirmasi</th>
                <th>Kasus Sembuh</th>
                <th>Kasus Meninggal</th>
            </tr>
        </thead>
        <tbody id='test'>

        </tbody>
        </table>
        </main>
        <br><br>
    </div>
    <br>
        <div class='text-right' id='backtotheback'>
            <a class="btn btn-info" href='/daftarkasus' >Kembali</a>
            </div>
            <br><br><br><br><br><br><br><br><br><br>
    
    
</body>

<script>
    $(document).ready(function() {
        $.ajax({
            url: "{% url 'listkasus:datainput' %}",
            success: function(data){
                var array_items = data.result;
                for(i = 0 ; i<array_items.length;i++){
                    var no = i+1 ;
                    var nama_daerah= array_items[i].nama_daerah;
                    var ktot= array_items[i].jumlah_total;
                    var ksem= array_items[i].kasus_sembuh;
                    var kded= array_items[i].kasus_meninggal;
                    $('#test').append("<tr> <td> "+ no + "</td><td>"+ nama_daerah +'</a></div> </td> <td> '+ktot+'</td> <td>'+ksem+"</td><td>"+kded+"</td></tr>")
                }
            }
    });  
});  
</script>
<script>
    $(document).ajaxComplete(function(){
        $('#daftar').DataTable();
        $('#daftar tbody').on('click','tr', function(){
            if($(this).hasClass("table-info")){
                $(this).removeClass("table-info");
            }
            else{
                $(this).addClass("table-info");
            }
        });  
    });
    
</script>



    {% endblock content %}
</html>

list_kasus/templates/list_kasus/kasusprovinsi.html
<html>
    {% extends 'base.html'%}
    {% load static %}
    {% block content %}
<head>
    {% block meta%}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"/>
 
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.23/datatables.min.js"></script>
    <style>
        footer,.navbar-brand,.nav-item{
        color: black;
        }
        #bodskuy{
            background-color: #4ECDC4;
        }
        table,th,td{
            border: black;
        }
        /* #daftar tbody tr.selected{
            color:black;
            background-color: #eeeeee;
        } */
    </style>
    {% endblock meta%}
</head>
<body>
    <div class = "titlee" style="margin-top: 100px;">
        <h1 class="text-center" style="color:white;"> Kasus COVID-19 Provinsi Indonesia </h1>
        
    </div>
    <div id="bodskuy">
        <br><br>
        <main class="container">
        <table class="table cell-border" id="daftar" style="color: black;">
        <thead style="color: black; background-color: gray;" >
            <tr>
                <th>No</th>
                <th>Provinsi</th>
                <th>Kasus Terkonfirmasi</th>
                <th>Kasus Sembuh</th>
                <th>Kasus Meninggal</th>
            </tr>
        </thead>
        <tbody id='test'>

        </tbody>
        </table>
        </main>
        <br><br>
    </div>
    <br>
        <div class='text-right' id='backtotheback'>
            <a class="btn btn-info" href='/daftarkasus' >Kembali</a>
            </div>
            <br><br><br><br><br><br><br><br><br><br>
    
    
</body>

<script>
    $(document).ready(function() {
        $.ajax({
            url: "{% url 'listkasus:data' %}",
            success: function(data){
                var array_items = data.data;
                for(i = 0 ; i<array_items.length-1;i++){
                    var no = i+1 ;
                    var prov= array_items[i].provinsi;
                    var ktot= array_items[i].kasusPosi;
                    var ksem= array_items[i].kasusSemb;
                    var kded= array_items[i].kasusMeni;
                    $('#test').append("<tr> <td> "+ no + "</td><td>" + prov +'</td> <td> '+ktot+'</td> <td>'+ksem+"</td><td>"+kded+"</td></tr>")
                }
            }
    });  
});  
</script>
<script>
    $(document).ajaxComplete(function(){
        $('#daftar').DataTable();
        $('#daftar tbody').on('click','tr', function(){
            if($(this).hasClass("table-info")){
                $(this).removeClass("table-info");
            }
            else{
                $(this).addClass("table-info");
            }
        });
        
    });
    
</script>



    {% endblock content %}
</html>

list_kasus/templates/list_kasus/listkasus.html
{% extends 'base.html'%}
{% load static %}
{% block meta%}
<link rel="stylesheet" href="{% static 'list_kasus/styleR.css' %}">
{% endblock meta%}

{% block content %}
    <div class ="container">

        <h2>Jumlah Kasus Covid di {{a.nama}} Saat Ini</h2>
        <div class ="row">
            <div class="col-md-4 text-center" >Kasus Terkonfirmasi <div class='card' id='jTotal' style='width:100%;'></div></div>
            <div class="col-md-4 text-center">Kasus Sembuh <div class='card' id='jSembuh' style='width:100%;'></div></div>
            <div class="col-md-4 text-center">Kasus Meninggal <div class='card' id='jMeninggal' style='width:100%;'></div></div>
        </div>
        <p></p>
        <p>Update Terakhir</p>
        <p style='margin-left: 10px;' id="apdet"></p>
        <br>
        <p>Cari Kasus di Daerahmu
              
        </p>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="asw" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Cari Daerahmu
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for i in list_kasus %}
              <a class="dropdown-item" href="{% url 'listkasus:kasusdetail' i.pk %}">{{i.nama_daerah}}</a>
                {% endfor %}
            </div>
          </div>
          <div>atau lihat semua daerah inputan</div>
          <a class ="btn btn-secondary" href="{% url 'listkasus:kasusinput' %}">daerah inputan user</a>
          <br>
          {% if user.is_authenticated %}
          <div>Mengetahui Jumlah Kasus di Daerahmu? Silahkan Tambahkan Kasus
              <a class="btn btn-info" href="{% url 'listkasus:tambahkasus' %}">Tambah Kasus</a>
          </div>
            {% else %}
            <div id="logon">Silahkan login untuk menambahkan kasus yang kamu ketahui di daerahmu, klik mengerti untuk menghilangkan pemberitahuan <p></p><a href ="#" id="ngerti" style="color:rgb(228, 59, 81);">Mengerti</a></div>

            {% endif %}
            <br>
            <div>
              <a class ="btn btn-secondary" href="{% url 'listkasus:kasusprovinsi' %}">berikut list kasus pada tiap provinsi di Indonesia</a>
            </div>
    </div>
   
    <br>
    <br><br><br>

    <script> 
      $(document).ready(function() {
        $.ajax({
          url:"{% url 'listkasus:dataIndonesia' %}",
          success: function(data){
            var items = data;
            var jTotal = items.positif;
            var jSembuh = items.sembuh;
            var jMeninggal = items.meninggal;
            var update = items.lastUpdate;
            var a = update.substring(0,10);
            var z = update.substring(11,19)
            $("#jTotal").append(jTotal)
            $("#jSembuh").append(jSembuh)
            $("#jMeninggal").append(jMeninggal)
            $("#apdet").append(a+" pukul "+ z)
          }
        });
      });
    </script>
    <script>
      $("#ngerti").click(function(){
        $("#logon").hide();
      });
    </script>

{% endblock content %}

list_kasus/templates/list_kasus/tambahkasus.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}

    {% block meta%}
    <link rel="stylesheet" href="{% static 'list_kasus/styleR.css' %}">
    {% endblock meta%}

{% block content %}
<div class="container" id="tambahkasus">
    <form method="post" id="kasus_form">
        {% csrf_token %}
        <div class="card" id = "tabel">
            <table class="table">
                <thead class="thead">
              <tr>
                <th scope="row">Keterangan</th>
                <th scope="row">Data</th>
                
              </tr>
            </thead>
            <tr>
                {{form}}
            </tr>
            </table>
            <div class="text-right">
            <button id="submit" type="submit" class="btn  btn-info ">Tambah</button>
            </div>
            

        </div>
        <div id="datacreate"></div>
        <div class='backbutton text-center'id='backtoyou'>
        <a class="btn btn-info" href='/daftarkasus' >Kembali</a>
        </div>
        
    </form>
    </div>
    <br>

    <script>
        $(document).on('submit','#kasus_form',function(event){
            event.preventDefault();
            event.stopImmediatePropagation();
            console.log("data succesfully created!")
            $.ajax({
                type:'POST',
                url: "/daftarkasus/tambahkasus/",
                data:{
                    nama_daerah:$('#namee').val(),
                    jumlah_total:$('#jumlahtotal').val(),
                    kasus_sembuh:$('#jumlahsembuh').val(),
                    kasus_meninggal:$('#jumlahmeninggal').val(),
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                },
                success:function(json){
                    document.getElementById("kasus_form").reset();
                    $('#datacreate').append("<p>  data for "+ json.nama_daerah+ " was created</p>")
                    console.log(json);
                },
            });
        })
        
    </script>
{% endblock content %}